version: 2

# Note: Generated protobuf files (gen/**/*.pb.go) should be committed to the repository.
# Do not regenerate them during the release process to avoid version-dependent diffs.
# To regenerate protobuf files during development, run:
#   protoc --go_out=. --go_opt=module=github.com/conallob/jira-beads-sync --proto_path=proto proto/jira.proto proto/beads.proto

before:
  hooks:
    # Run tests
    - go test ./...
    # Tidy dependencies
    - go mod tidy

builds:
  - id: jira-beads-sync
    main: ./cmd/jira-beads-sync
    binary: jira-beads-sync
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CLAUDE.md

nfpms:
  - id: packages
    package_name: jira-beads-sync
    vendor: Conall O'Brien
    homepage: https://github.com/conallob/jira-beads-sync
    maintainer: Conall O'Brien <conall@conall.net>
    description: Sync Jira task trees with beads issues (bidirectional)
    license: BSD-3-Clause
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: LICENSE
        dst: /usr/share/doc/jira-beads-sync/LICENSE
      - src: README.md
        dst: /usr/share/doc/jira-beads-sync/README.md
      - src: CLAUDE.md
        dst: /usr/share/doc/jira-beads-sync/CLAUDE.md
    rpm:
      group: Development/Tools
      compression: lzma
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - 'typo'
  groups:
    - title: Features
      regexp: '^feat:'
      order: 0
    - title: Bug Fixes
      regexp: '^fix:'
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: conallob
    name: jira-beads-sync
  draft: false
  prerelease: auto
  mode: replace
  name_template: "Release {{.Tag}}"
  header: |
    ## What's Changed

    Jira Beads Sync - Bidirectional synchronization between Jira task trees and beads issues.

    ### Installation

    **Homebrew (macOS/Linux):**
    ```bash
    brew install conallob/tap/jira-beads-sync
    ```

    **Debian/Ubuntu:**
    ```bash
    curl -LO https://github.com/conallob/jira-beads-sync/releases/download/{{ .Tag }}/jira-beads-sync_{{ .Version }}_amd64.deb
    sudo dpkg -i jira-beads-sync_{{ .Version }}_amd64.deb
    ```

    **RHEL/Fedora/CentOS:**
    ```bash
    curl -LO https://github.com/conallob/jira-beads-sync/releases/download/{{ .Tag }}/jira-beads-sync_{{ .Version }}_x86_64.rpm
    sudo rpm -i jira-beads-sync_{{ .Version }}_x86_64.rpm
    ```

    **Container:**
    ```bash
    docker pull ghcr.io/conallob/jira-beads-sync:{{ .Version }}
    docker run ghcr.io/conallob/jira-beads-sync:{{ .Version }} help
    ```

    **Manual (macOS):**
    ```bash
    # For Apple Silicon (M1/M2/M3)
    curl -LO https://github.com/conallob/jira-beads-sync/releases/download/{{ .Tag }}/jira-beads-sync_{{ .Version }}_Darwin_arm64.tar.gz
    tar xzf jira-beads-sync_{{ .Version }}_Darwin_arm64.tar.gz
    sudo mv jira-beads-sync /usr/local/bin/

    # For Intel
    curl -LO https://github.com/conallob/jira-beads-sync/releases/download/{{ .Tag }}/jira-beads-sync_{{ .Version }}_Darwin_x86_64.tar.gz
    tar xzf jira-beads-sync_{{ .Version }}_Darwin_x86_64.tar.gz
    sudo mv jira-beads-sync /usr/local/bin/
    ```

    **Manual (Linux):**
    ```bash
    # For x86_64
    curl -LO https://github.com/conallob/jira-beads-sync/releases/download/{{ .Tag }}/jira-beads-sync_{{ .Version }}_Linux_x86_64.tar.gz
    tar xzf jira-beads-sync_{{ .Version }}_Linux_x86_64.tar.gz
    sudo mv jira-beads-sync /usr/local/bin/

    # For ARM64
    curl -LO https://github.com/conallob/jira-beads-sync/releases/download/{{ .Tag }}/jira-beads-sync_{{ .Version }}_Linux_arm64.tar.gz
    tar xzf jira-beads-sync_{{ .Version }}_Linux_arm64.tar.gz
    sudo mv jira-beads-sync /usr/local/bin/
    ```

    **Windows:**
    Download the `.zip` file for your architecture and extract it.

    ### Usage

    ```bash
    jira-beads-sync convert jira-export.json
    ```

brews:
  - name: jira-beads-sync
    repository:
      owner: conallob
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/conallob/jira-beads-sync"
    description: "Sync Jira task trees with beads issues (bidirectional)"
    license: "BSD-3-Clause"
    install: |
      bin.install "jira-beads-sync"
    test: |
      system "#{bin}/jira-beads-sync version"

dockers:
  - image_templates:
      - "ghcr.io/conallob/jira-beads-sync:{{ .Version }}-amd64"
      - "ghcr.io/conallob/jira-beads-sync:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  - image_templates:
      - "ghcr.io/conallob/jira-beads-sync:{{ .Version }}-arm64"
      - "ghcr.io/conallob/jira-beads-sync:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  - name_template: "ghcr.io/conallob/jira-beads-sync:{{ .Version }}"
    image_templates:
      - "ghcr.io/conallob/jira-beads-sync:{{ .Version }}-amd64"
      - "ghcr.io/conallob/jira-beads-sync:{{ .Version }}-arm64"

  - name_template: "ghcr.io/conallob/jira-beads-sync:latest"
    image_templates:
      - "ghcr.io/conallob/jira-beads-sync:latest-amd64"
      - "ghcr.io/conallob/jira-beads-sync:latest-arm64"
